// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYtk4OtyJKJIFkNBK1KmJ7nD1NCspSLw',
    appId: '1:1015132307983:android:0d2397a6d114871856997a',
    messagingSenderId: '1015132307983',
    projectId: 'flutter-firebase-money-app',
    storageBucket: 'flutter-firebase-money-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAypzPHddnaTzl5ypwRN_CEVkbjzfG9w0',
    appId: '1:1015132307983:ios:9471ac5e66d5521056997a',
    messagingSenderId: '1015132307983',
    projectId: 'flutter-firebase-money-app',
    storageBucket: 'flutter-firebase-money-app.firebasestorage.app',
    iosClientId:
        '1015132307983-0c84pf1kti9sq27k352kh7kq6pra5nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMoneyManagementApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCRwXN4ii-84eLgYBUpvLzfnSgFmvRXnq0",
    authDomain: "flutter-firebase-money-app.firebaseapp.com",
    projectId: "flutter-firebase-money-app",
    storageBucket: "flutter-firebase-money-app.firebasestorage.app",
    messagingSenderId: "1015132307983",
    appId: "1:1015132307983:web:8d8ad849a2e126bd56997a",
  );
}
